export const title6 = "Психоэмоциональное (душевное, духовное) здоровье";
export const question6 = [
  {
    question: "Депрессия",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Тревога",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Разочарование",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Одиночество",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Деморализация (из-за неверия) ",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Боязнь мобильности",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Неуверенность в себе",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Чувство печали",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Суицидные мысли",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Страх смерти",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Нервные срывы",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Галлюцинации",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Нарушения социальной адаптации",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Отсутствие критики",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
];
