export const title1 = "Центральная нервная система";
export const question1 = [
  [
    {
      caption: "Нервная система",
      question: "Судороги разной интенсивности",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Дрожь в руках, коленях, ногах разной интенсивности",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "«Вибрации» внутри тела",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Озноб",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Подергивание пальцев рук и ног",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Тревожный сон или бессонница",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "«Туманность» или спутанность сознания",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Забывчивость",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Онемение конечностей (кончиков пальцев)",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Паралич Белла, паралич лицевого нерва,  перекошенность лица",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
  ],

  [
    {
      caption: "Речь",
      question: "Невнятная речь",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Признаки инсульта",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
  ],
  [
    {
      caption: "Боли",
      question: "Головные боли (мигрени)",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Боли в нижней челюсти",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Боли в скулах",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Боль в шее",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
  ],
  [
    {
      caption: "Нарушение сна",
      question: "Появившееся апноэ, храп во сне с временной остановкой дыхания",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Бессонница",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Постоянная усталость (вялость)",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Психологические расстройства в темноте",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Беспокойный тревожный сон",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Частые пробуждения",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Плохие сны ",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Нарушение процесса засыпания",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Трудности с засыпанием в привычной позе",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
  ],
  [
    {
      caption: "Нарушение координации движений",
      question: "В покое",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "При ходьбе",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
  ],
  [
    {
      caption: "Психоэмоциональное (душевное, духовное) здоровье",
      question: "Депрессия",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Тревога",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Разочарование",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Одиночество",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Деморализация (из-за неверия) ",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Боязнь мобильности",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Неуверенность в себе",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Чувство печали",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Суицидные мысли",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Страх смерти",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Нервные срывы",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Галлюцинации",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Нарушения социальной адаптации",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Отсутствие критики",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
  ],
  [
    {
      caption: "Память",
      question: "Потеря кратковременной памяти",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
    {
      question: "Воспоминания и подбор слов",
      placeholder: "0-100",
      type: "input text",
      answer: "",
      schedule: [...Array(31).fill(0)],
    },
  ],
];
