export const title1 = "Центральная нервная система";
export const question1 = [
  {
    caption: "Нервная система",
    question: "Судороги разной интенсивности",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Дрожь в руках, коленях, ногах разной интенсивности",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "«Вибрации» внутри тела",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Озноб",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Подергивание пальцев рук и ног",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Тревожный сон или бессонница",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "«Туманность» или спутанность сознания",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Забывчивость",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Онемение конечностей (кончиков пальцев)",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
  {
    question: "Паралич Белла, паралич лицевого нерва,  перекошенность лица",
    placeholder: "0-100",
    type: "input text",
    answer: "",
    schedule: [...Array(31).fill(0)],
  },
];
